from database.database import setupDatabase, resetDatabase, engine
from database import models, control

resetDatabase()
setupDatabase()

robo = control.addCourseCategory("Robo")
primary = control.addCourseCategory("Primary")
game = control.addCourseCategory("Game")
web = control.addCourseCategory("Web")
python = control.addCourseCategory("Python")

control.addCourse("Arduino Junior", robo.id)
control.addCourse("Middle Embedded", robo.id)
control.addCourse("Pro Embedded", robo.id)
control.addCourse("Senior Embedded", robo.id)
control.addCourse("Expert Embedded", robo.id)
control.addCourse("Juno Bricks", primary.id)
control.addCourse("IT Start", primary.id)
control.addCourse("Intro Coding", primary.id)
control.addCourse("Construct", game.id)
control.addCourse("Unity Beginner", game.id)
control.addCourse("Unity 2D", game.id)
control.addCourse("Unity 3D", game.id)
control.addCourse("Unity Pro", game.id)
control.addCourse("Web Beginner", web.id)
control.addCourse("Web Junior", web.id)
control.addCourse("Web Middle", web.id)
control.addCourse("Web FullStack", web.id)
control.addCourse("Python Beginner", python.id)
control.addCourse("Python Junior", python.id)
control.addCourse("Python Middle", python.id)

# student = control.addStudent("AleksGoncharuk1")
# teacher = control.addTeacher("AleksGoncharuk")

# group1 = control.addGroup("ПТ", 18, 1, 1, 1)
# input()
# control.addGroupStudent("Санечек", "agoncharuk", group1.id)
# input()
# control.loginGroupStudent("agoncharuk", student.id, group1.id)
# # control.joinStudentToGroup(student.id, group1.id)

# print([student.student_name for student in control.getGroupStudents(group1.id)])
# input()
# control.kickGroupStudent(student.id, group1.id)
# print(control.getGroupStudents(group1.id))

# student1 = control.addStudent("AleksGoncharuk", "Гончарук Олександр")
# group2 = control.addGroup("ЧТ", 18, 1, 4, 1)
# control.joinStudentToGroup(student1.id, group2.id)
# control.joinStudentToGroup(student1.id, group1.id)
# # control.joinStudentToGroup(student.id, group.id)

# print([(group.course.name, group.day) for group in control.getStudentGroups(student1.username)])
# # print([(group.course.name, group.day) for group in control.getTeacherGroups(teacher.id)])

# print([(group.course.name, group.day, balance) for group, balance in control.getStudentBalances(student1.id)])
# control.changeStudentBalanceInGroup(student1.id, group1.id, 10)
# control.changeStudentBalanceInGroup(student1.id, group2.id, 11)
# print([(group.course.name, group.day, balance) for group, balance in control.getStudentBalances(student1.id)])
# control.changeStudentBalanceInGroup(student1.id, group1.id, -4)
# control.changeStudentBalanceInGroup(student1.id, group2.id, -1)
# print([(group.course.name, group.day, balance) for group, balance in control.getStudentBalances(student1.id)])